{% set versions = {
    "2.3.8": "859b723666eeac7df018209d66045c9853b50b4218cecadb794e2359619ebce7"
} %}

{% set version = environ.get('COMMIT_VERSION', None) %}
{% set version = version or versions.keys()|first %}
{% set version = version|string %}

package:
  name: {{ environ.get('ANACONDA_PACKAGE', 'openmotif')|string|lower }}
  version: {{ environ.get('ANACONDA_VERSION', version)|replace("-", ".") }}

source:
  url: https://downloads.sourceforge.net/project/motif/Motif%20{{ version }}%20Source%20Code/motif-{{ version }}.tar.gz
  {% if versions.get(version, None) %}
  sha256: {{ versions.get(version) }}
  {% endif %}
  patches:
    - 0003_fix_ftbfs_binutils-gold.patch  # [linux]

requirements:
  build:
    - make
    - pkg-config
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - flex
    - freetype
    - fontconfig
    - libpng
    - zlib
    - libjpeg-turbo
    - "xorg-libx11>1.8"
    - xorg-libxt
    - xorg-libxext
    - xorg-libxft
    - xorg-xbitmaps
    - xorg-libxp
    - xorg-libxmu
    - xorg-makedepend
    - libiconv

  run:
    - freetype
    - fontconfig
    - libpng
    - "xorg-libx11>1.8"
    - xorg-libxt
    - xorg-libxext
    - xorg-libxft
    - xorg-libxp
    - xorg-libxmu
    - libiconv

test:
  commands:
    - 'test "`uil 2>&1| tr -d ''\n''`" = "Severe: no source file specified"'

about:
  home: http://motif.ics.com
  license: LGPL-2.1
  license_family: LGPL
  license_file: COPYING
  summary: 'Motif user interface component toolkit.'

extra:
  recipe-maintainers:
    - meiyasan
