travis:
  secure:
    BINSTAR_TOKEN: JjNa7L8rmg4VBybZyro7sLa94jcBBi/314OQyGALbvMJdPmNC3L0wHOPIqfrKyvdlXVTAnh8Qu85gSKkIs8BylqDe0IRaNHS2YMHhRVfllXFDCRpjsiTQtTJS6d4MzqwVzsi5nGWKh8tOmvPy3pXFqwquEZFIPQGLQjfoDbF69n9I9SMh99tGxyoJypvvXD34/qrCJ7OBPQIF1TeNFJg6+D9+ORtnwhG4DdWPxBKKlkCHikrvPFC2Z2meZDYA+RpzOkaDOptX3dhb83oO3OS0jnNyRIjut1Luuo7znxGVHwx9HpBB+C35G4VJV+CDYCQz7dgA19g5AdfGIIz7JrDUQ3igLiyzq2MZHJIze9Sb02S3kT+w4iaPi+ZpfozOjFWu0vUKisqiL+OlgD9QA3JSRQR+7slNBfHp3v1zq5emhFX11B0GvyoNgvelBMPUQ5jpAs1uEwkcOsPoOY0L5K1Mefue+E0oGfj8+CbVHP3fwwq5zxX/nDBnre6GdTvjnoL1AM6BNNDz5xL1Yp6VpJFu/JnovqbuSxFhE5jqSxV0pSrLIPTXmA9DkVtnbTR/T/1NZyO0hSpFv5vElCnjIZgXzQ5zK90wq4mZRC+N4Hrha11m+CdbfEQwkyah1Cr6N7LBWE0+W7JRaH67l+AzZqgOKAskwRPPeUzfsMh9jpG0vs=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
